### ISSUE TITLE
mdns-discovery might return an error if network doesn't support IPv6

### ISSUE THREAD

**Issue by silvanocerza** [arduino/mdns-discovery#24]

**Comment by silvanocerza** [comment]
This issue is hard to reproduce, we need to understand what the actual network configurations are causing this.
For more information I suggest contacting @sebromero, he has access to a network that causes this exact issue and it will be certainly helpful troubleshooting together.

**Comment by per1234** [comment]
Since this issue is so lacking in information, I'm going to close it in favor of the more recent duplicate https://github.com/arduino/mdns-discovery/issues/25
